In [1]:
import numpy as np
from sympy import *
from scipy.optimize import approx_fprime
from scipy.optimize import minimize

### Уровень 0:


Посчитайте частные производные функций:

1) $f(x,y)=2x^2y^3 + 1/x + y^2x + 7$

In [2]:
def func(x):
    "Coordinate vector `x` should be an array of size two."
    y = x[1]
    x = x[0]
    
    return 2*x**2*y**3 + 1/x + y**2*x + 7

x = np.ones(2)
eps = np.sqrt(np.finfo(float).eps)

approx_fprime(x, func, [eps, eps])

array([4.        , 8.00000012])

А для этой функции также градиент в точке $(1,2)$

In [3]:
x = np.array([1,2])
approx_fprime(x, func, [eps, eps])

array([35.00000024, 28.00000024])

2) $f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

In [4]:
def func(x):
    "Coordinate vector `x` should be an array of size two."
    y = x[1]
    x = x[0]
    
    return x**2*y - sin(x*y) + cos(x**2) + 6*y

x = np.ones(2)
eps = np.sqrt(np.finfo(float).eps)

approx_fprime(x, func, [eps, eps])

array([-0.22324431,  6.45969766])

### Уровень 1:
Градиентный спуск своими руками:

In [5]:
def f(x):
    return (x[0]**2) + (x[1]**2)

x = np.array([100, 200])
learning_rate = 0.1
eps = np.sqrt(np.finfo(float).eps)


for i in range(100):
    # Calculate gradient
    grad = approx_fprime(x, f, [eps, eps])   
    
    # Update x with gradient
    x = x - grad * learning_rate

print("Минимум достигается в: ", x)
print("Значение функции в минимуме: ", f(x))

Минимум достигается в:  [1.29197811e-08 3.32901401e-08]
Значение функции в минимуме:  1.2751541739575584e-15


Проверка с помощью встроенной функции numpy:

In [6]:
x = np.array([100, 200])
res = minimize(f, x, method='Nelder-Mead', options={'xtol':1e-8, 'disp':True})

print("Минимум достигается в: ", res.x)
print("Значение функции в минимуме: ", f(res.x))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 85
         Function evaluations: 164
Минимум достигается в:  [ 3.31391559e-09 -1.82888492e-09]
Значение функции в минимуме:  1.4326856592347756e-17
